---
title: "DNM numbers in twins and unrelated children"
author: "Jakob Goldmann"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)

colSpec <- cols(SampleID = col_character(), 
                familyNr = col_character(), 
                batch = col_character(),
                no.DNMs = col_integer())
samples_c1 <-  read_delim(file = here("dnmvar-compendium/data/samples_c1.tsv"),  delim = "\t", col_types = colSpec)
samples_c2 <-  read_delim(file = here("dnmvar-compendium/data/samples_c2.tsv"),  delim = "\t", col_types = colSpec)
samples_c3 <-  read_delim(file = here("dnmvar-compendium/data/samples_c3.tsv"),  delim = "\t", col_types = colSpec)
samples_c4 <-  read_delim(file = here("dnmvar-compendium/data/samples_c4.tsv"),  delim = "\t", col_types = colSpec)
samples_c3b <- read_delim(file = here("dnmvar-compendium/data/samples_c3b.tsv"), delim = "\t", col_types = colSpec)


```


Functions for formatting twin versus PAMUC data
```{r}
getTwins <- function(dnmData101) {
  dnmData101 %>% 
    add_count(familyNr) %>% 
    filter(n==2) %>% 
    group_by(familyNr) %>% 
    do(mutate(., 
              twins = (diff(fathersAgeAtConceptionInYears)==0) & (diff(mothersAgeAtConceptionInYears)==0))) %>% 
    filter(twins) %>%
    filter(familyNr != "101-306") %>% #weirdly annotated in 101 set
    ungroup() %>%
    dplyr::select(-twins)
}

getPamucs <- function(dnmData101, maxAgeDiff) {
  twinFamilies <- 
    dnmData101 %>% 
    getTwins() %>%
    pull(familyNr)
  
  dnmData101 %>%
    filter(!(familyNr %in% twinFamilies)) %>%
    arrange(fathersAgeAtConceptionInYears, mothersAgeAtConceptionInYears) %>% 
    mutate(ageClusterNumber=
             as.character(
               cutree(
                 hclust(dist(cbind(fathersAgeAtConceptionInYears, mothersAgeAtConceptionInYears), method = "manhattan")), 
                 h=maxAgeDiff/365)))  %>% 
    add_count(ageClusterNumber) %>%
    filter(n==2)
}

assembleTwinsVsUnrelated <- 
  function(dnmData101, maxAgeDiff) {
    twins <- 
      getTwins(dnmData101) %>% 
      group_by(familyNr) %>%
      nest() %>%
      mutate(no.pairs=map_int(data, ~nrow(.))) %>%
      filter(no.pairs==2) %>%
      mutate(diff_n=map_int(data, ~max(abs(diff(.$no.DNMs)))),
             set = "dizygote twins") %>% 
      mutate(group = as.character(familyNr)) %>%
      select(-familyNr)
    
    pamucs <- 
      getPamucs(dnmData101, maxAgeDiff) %>% 
      group_by(ageClusterNumber) %>%
      nest() %>%
      mutate(no.pairs=map_int(data, ~nrow(.))) %>%
      filter(no.pairs==2) %>%
      mutate(diff_n=map_int(data, ~max(abs(diff(.$no.DNMs)))),
             set = "PAMUCs") %>% 
      mutate(group = map_chr(data, ~do.call(paste, as.list(.$familyNr)))) %>%
      select(-ageClusterNumber)
    
    bind_rows(
      twins,
      pamucs
    )
  }
```

Getting main data like in thesis version, except for applying filters for unique genome regions:
```{r}
maxAgeDiff <- 43

twinsVsUnrelated <-
  rbind(
    assembleTwinsVsUnrelated(samples_c1, 
                             maxAgeDiff) %>% 
      mutate(cohort="cohort1"), 
    assembleTwinsVsUnrelated(samples_c2, maxAgeDiff) %>% 
      mutate(cohort="cohort2"),
    assembleTwinsVsUnrelated(samples_c3, maxAgeDiff) %>% 
      mutate(cohort="cohort3")
    ) %>%
  mutate(fatherAge=map_dbl(data, ~mean(.$fathersAgeAtConceptionInYears)),
         cohort=fct_inorder(cohort))
```


Figures
-------

Visualization of the data for all cohorts apart
```{r}
twinsVsUnrelated %>% 
  filter(set=="dizygote twins") %>% 
  mutate(fatherAge=map(data, ~.$fathersAgeAtConceptionInYears), no.DNMs=map(data, ~.$no.DNMs), group=seq_along(no.pairs)) %>% 
  dplyr::select(-data) %>% 
  unnest() %>% 
  ggplot(aes(x=fatherAge, y=no.DNMs, group=group)) + 
  geom_point(col="#008000") + 
  geom_path(col="#008000") +
  labs(x="Father's age at conception in years",
       y="Dizygotic twins' no. DNMs") + 
  facet_wrap(~cohort) + 
  ggpubr::theme_pubr()

twinsVsUnrelated %>% 
  filter(set=="PAMUCs") %>% 
  mutate(fatherAge=map(data, ~.$fathersAgeAtConceptionInYears), no.DNMs=map(data, ~.$no.DNMs), group=seq_along(no.pairs)) %>% 
  dplyr::select(-data) %>% 
  unnest() %>% 
  ggplot(aes(x=fatherAge, y=no.DNMs, group=group)) + 
  geom_point(col="#2b2b2b") + 
  geom_path(col="#2b2b2b") +
  labs(x="Father's age at conception in years",
       y="PAMUCs' no. DNMs") + 
  facet_wrap(~cohort) + 
  ggpubr::theme_pubr()

give.n <- function(x){
    return(data.frame(y = -1, label = paste0("n=", length(x))))
}
twinsVsUnrelated %>%
  ggplot(aes(x=cohort, y=diff_n, col=set)) + 
  geom_violin(aes(fill=set)) + 
  geom_boxplot(width=0.9)+
  scale_color_manual(values = c("PAMUCs"="#2b2b2b", "dizygote twins"="#008000"), 
                     labels = c("PAMUCs"="PAMUCs", "dizygote twins"="Dizygotic twins"), 
                     guide="none") + 
  scale_fill_manual(values = c("PAMUCs"="#2b2b2b", "dizygote twins"="#008000"), 
                    labels = c("PAMUCs"="PAMUCs", "dizygote twins"="Dizygotic twins")) + 
  stat_summary(fun.data = give.n, geom = "text", position = position_dodge(width = 0.9)) + 
  labs(x="", y="Difference in no. DNMs",
       fill="Set") + 
  ggpubr::theme_pubr() + 
  ggsignif::geom_signif(annotations = c("p=0.13", "p=0.22", "p=0.51"),   # see below for the calculation of these values
                        y_position = c(22, 35, 40), xmin=c(0.8,1.8,2.8), xmax=c(1.2,2.2,3.2),
                        col="black")

```

Numbers
-------

```{r}
twinsVsUnrelated %>% 
  group_by(set, cohort) %>% 
  summarize(medDiff=median(diff_n), 
            mx=max(diff_n), 
            mn=min(diff_n))
twinsVsUnrelated %>% 
  group_by(set, cohort) %>% 
  count()
```

Tests
-----

First, are twin differences related to paternal age?
```{r}
# linear regression
twinsVsUnrelated %>%
  filter(set=="dizygote twins") %>%
  dplyr::select(-data) %>% 
  with(lm(diff_n~fatherAge)) %>% 
  broom::tidy() %>% 
  filter(term=="fatherAge") %>% 
  pull(p.value)

# heteroscedacity
twinsVsUnrelated %>%
  mutate(fatherAge=map_dbl(data, ~mean(.$fathersAgeAtConceptionInYears))) %>%
  filter(set=="dizygote twins") %>%
  dplyr::select(-data) %>%
  lm(diff_n~fatherAge, data=.) %>%
  lmtest::bptest() %>% 
  with(.$p.value)
```

Second, are the twin differences of PAMUCs larger than of twins?
```{r}
twinsVsUnrelated %>% 
  group_by(cohort) %>% 
  do(with(.,
          broom::tidy(wilcox.test(diff_n~set, 
                                  alternative="less", 
                                  exact=FALSE))))    # use a normal approximation, as there are ties in the data
twinsVsUnrelated %>% 
  with(.,broom::tidy(wilcox.test(diff_n~set, 
                                 alternative="less", 
                                 exact=FALSE)))
```

Third, are PAMUC differences related to paternal age?
```{r}
#linear regression
twinsVsUnrelated %>%
  mutate(fatherAge=map_dbl(data, ~mean(.$fathersAgeAtConceptionInYears))) %>% 
  filter(set!="dizygote twins") %>%
  dplyr::select(-data) %>% 
  with(lm(diff_n~fatherAge)) %>% 
  broom::tidy() %>% 
  filter(term=="fatherAge") %>% 
  pull(p.value)

#heteroscedacity
twinsVsUnrelated %>%
  mutate(fatherAge=map_dbl(data, ~mean(.$fathersAgeAtConceptionInYears))) %>%
  filter(set!="dizygote twins") %>%
  dplyr::select(-data) %>%
  lm(diff_n~fatherAge, data=.) %>%
  lmtest::bptest() %>% 
  with(.$p.value)

```


Table
-----

```{r}
twinsVsUnrelated_tbl <- 
  twinsVsUnrelated %>%
  dplyr::select(-data)
write_delim(twinsVsUnrelated_tbl,
            path = here("compendium/analyses/twinsVsPAMUC/twinsVsPAMUC.tsv"),
            delim = "\t")
```



Supplementary: TwinsVsPamuc power simulation
--------------------------------------------

```{r}
library(rptR)
library(foreach)
```

Function for simulating a family effect
```{r}
simulateFamEf <- function(samples_c1, varCompFam=0.05) {
  mdl <- glm(no.DNMs ~ fathersAgeAtConceptionInYears + mothersAgeAtConceptionInYears,
             data = samples_c1, 
             family = poisson)
  predictedNoDNMs <- predict.glm(mdl, type = "response")
  varFam <- varCompFam*var(samples_c1$no.DNMs)
  varResi <- var(residuals(mdl, type = "response"))
  varErr <- varResi - varFam
  
  familyEffects <- rnorm(length(unique(samples_c1$familyNr)), sd=sqrt(varFam))
  names(familyEffects) <- unique(samples_c1$familyNr)
  residualEffects <- rnorm(nrow(samples_c1), sd=sqrt(varErr))
  
  samples_c1 %>%
    mutate(simFamEf = round(predictedNoDNMs + residualEffects + familyEffects[familyNr]))
}
```

Doublechecking if the function works as intended
```{r}
checkSims <- function(times, varCompFam = 0.2) {
  withinCI <- 
    foreach(1:times,
            .combine = c) %do% {
              sim <- simulateFamEf(samples_c3, varCompFam)
              varCompConfInt <-
                rpt(simFamEf ~ fathersAgeAtConceptionInYears + mothersAgeAtConceptionInYears + (1|familyNr),
                    data = sim,
                    grname=c("familyNr"),
                    nboot=100,
                    npermut = 0,
                    adjusted = FALSE,
                    datatype = "Gaussian",
                    parallel = TRUE) %>% 
                pluck("CI_emp")
              varCompFam > varCompConfInt[,1] & varCompFam < varCompConfInt[,2]
            }
  table(withinCI)
}

checkSims(20) # should be less than 10% outside of CIs
checkSims(20, 0.05)
```


Run the simulations for comparing twins versus PAMUCs
```{r}
compareTwinDifferences <- function(samples_c3, varComp) {
  simulateFamEf(samples_c3, varComp) %>%
    mutate(no.DNMs = as.integer(simFamEf)) %>%
    assembleTwinsVsUnrelated(maxAgeDiff = maxAgeDiff) %>%
    with(broom::tidy(wilcox.test(diff_n~set))) %>%
    mutate(varComp = varComp)
}

set.seed(1234)
varCompSimulation <- 
  foreach(varComp = c(0.05, 0.1, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5),
          .combine = bind_rows) %do% {
            foreach(1:50,
                    .combine = bind_rows) %do% 
              compareTwinDifferences(samples_c3, varComp)
          }
```


```{r}
ggplot(varCompSimulation, aes(x=varComp,y=p.value, group=varComp)) + 
  geom_boxplot() + 
  labs(x="family component",
       y="p-value for DNM count difference")

varCompSimulation %>% 
  group_by(varComp) %>% 
  summarize(fracSignif=sum(p.value<=0.05)/length(p.value))

```


