---
title: "Variance Component Estimations"
author: "Jakob Goldmann"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(rptR)

colSpec <- cols(SampleID = col_character(), 
                familyNr = col_character(), 
                batch = col_character(),
                no.DNMs = col_integer())
samples_c1  <- read_delim(file = here("dnmvar-compendium/data/samples_c1.tsv"),  delim = "\t", col_types = colSpec)
samples_c2  <- read_delim(file = here("dnmvar-compendium/data/samples_c2.tsv"),  delim = "\t", col_types = colSpec)
samples_c3  <- read_delim(file = here("dnmvar-compendium/data/samples_c3.tsv"),  delim = "\t", col_types = colSpec)
samples_c4  <- read_delim(file = here("dnmvar-compendium/data/samples_c4.tsv"),  delim = "\t", col_types = colSpec)
samples_c3b <- read_delim(file = here("dnmvar-compendium/data/samples_c3b.tsv"), delim = "\t", col_types = colSpec)

```



Function for running the variance component estimations
```{r}
calcRelativeVarCorsWithCi <- function(dnms, 
                                      withBatch=TRUE,
                                      nsim = 500) {
  doublecheckFitConvergence(dnms, withBatch) # assert that we can ignore model convergence warnings
  if(withBatch) {
    estim <-
      rpt(no.DNMs ~ fathersAgeAtConceptionInYears + mothersAgeAtConceptionInYears + (1|familyNr) + (1|batch),
          data = dnms,
          grname=c("familyNr", "batch", "Fixed", "Residual"),
          nboot=nsim,
          npermut = 0,
          adjusted = FALSE,
          datatype = "Gaussian",
          parallel = TRUE)
  } else {
    estim <-
      rpt(no.DNMs ~ fathersAgeAtConceptionInYears + mothersAgeAtConceptionInYears + (1|familyNr),
          data = dnms,
          grname=c("familyNr", "Fixed", "Residual"),
          nboot=nsim,
          npermut = 0,
          adjusted = FALSE,
          datatype = "Gaussian",
          parallel = TRUE)
  }
  res <- 
    bind_cols(estimate=as.double(estim$R), 
              estim$CI_emp %>% rownames_to_column()) %>% 
    dplyr::rename(factor=rowname, 
                  relVar.total=estimate, 
                  lower.total=`2.5%`, 
                  upper.total=`97.5%`)
  return(res)
}

doublecheckFitConvergence <- function(dnms, 
                                      withBatch=TRUE) {
  # For some model fits, a convergence warning might be thrown sounding like this:
  #
  #         In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  #           Model failed to converge with max|grad| = 0.00333311 (tol = 0.002, component 1)
  #
  # This can in principle be overcome by chosing the alternative optimzation option 'bobyqa' (https://stackoverflow.com/questions/21344555/convergence-error-for-development-version-of-lme4).
  # Nevertheless, the estimates obtained by both the standard optimization and the 'bobyqa' optimization are exremely close to each other. In order to not reimplement the functionality of the 'rptr'-package with the bobyqa-option, we here assert that both estimates are close to identical.
  if(withBatch) {
    suppressWarnings(
      opti_std <- 
      lme4::lmer(no.DNMs ~ fathersAgeAtConceptionInYears + mothersAgeAtConceptionInYears + (1|familyNr) + (1|batch),
             data = dnms) %>% 
      broom.mixed::tidy()
    )
    opti_bob <- 
      lme4::lmer(no.DNMs ~ fathersAgeAtConceptionInYears + mothersAgeAtConceptionInYears + (1|familyNr) + (1|batch),
             data = dnms,
             control = lme4::lmerControl(optimizer="bobyqa")) %>% 
      broom.mixed::tidy()
  } else {
    suppressWarnings(
      opti_std <- 
      lme4::lmer(no.DNMs ~ fathersAgeAtConceptionInYears + mothersAgeAtConceptionInYears + (1|familyNr),
             data = dnms) %>% 
      broom.mixed::tidy()
    )
    opti_bob <- 
      lme4::lmer(no.DNMs ~ fathersAgeAtConceptionInYears + mothersAgeAtConceptionInYears + (1|familyNr),
             data = dnms,
             control = lme4::lmerControl(optimizer="bobyqa")) %>% 
      broom.mixed::tidy()
  }
  stopifnot(
      near(opti_std$estimate, opti_bob$estimate, tol=1e-3)
    )
}
```

Functions for augmentative statistics
```{r}
familyStats <- function(autism1, tblHdr = "no.DNMs") {
  no.offspring <- sum(autism1[, tblHdr]>0)
  no.familys <- autism1 %>% group_by(familyNr) %>% summarize(no.children = length(SampleID)) %>% filter(no.children>1) %>% nrow()
  no.childrenPerFamily <- autism1 %>% group_by(familyNr) %>% summarise(familySize=length(SampleID)) %>% pull(familySize) %>% mean()
  no.muts <- sum(autism1[, tblHdr])
  tibble(no.familys=no.familys, 
         no.childrenPerFamily = no.childrenPerFamily, 
         no.muts.pp=no.muts/no.offspring)
}

```

Doing the calculations
```{r}
set.seed(4321)

allEstimates <- 
  bind_rows(
    samples_c1 %>% calcRelativeVarCorsWithCi() %>% mutate(set = "cohort1"),
    samples_c2 %>% calcRelativeVarCorsWithCi(withBatch = FALSE) %>% mutate(set = "cohort2"),
    samples_c3 %>% calcRelativeVarCorsWithCi() %>% mutate(set = "cohort3"),
    samples_c4 %>% calcRelativeVarCorsWithCi(withBatch = FALSE) %>% mutate(set = "cohort4")
  ) 
# When running the above command, the following warnings and messages might arise:
# 
# 1. Message "boundary (singular) fit: see ?isSingular"
#    This message is lauched because it is difficult to estimate the batch effect for the inova2 data given the experimental distribution of samples into batches and the estimate is close to zero. See also here: https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#singular-models-random-effect-variances-estimated-as-zero-or-correlations-estimated-as---1
#
# 2. Warning "In rptGaussian(formula, grname, data, CI, nboot, npermut, parallel,  : 1 rows containing missing values were removed"
#    This warning is lauched because of batch information for one offspring of the three-offspring family 102-01507 in the inova2 dataset is missing. The estimation of the batch effect is therefore based on the remaining data points.
#
# 3. Several warnings like "In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :  Model failed to converge with max|grad| = 0.00302837 (tol = 0.002, component 1)"
#    These warnings indicate difficulties of the standard fitting algorithm to accurately estimate the parameters. Following the recommendations for dealing with these warnings, we control that the parameter estimations are close to equal to the results obtained by another estimator (without warnings) in the function 'doublecheckFitConvergence' defined above. See also  https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#troubleshooting



familyEstimates <-
  allEstimates %>%
  filter(factor == "familyNr") %>%
  mutate(includesBatch = c(TRUE, FALSE, TRUE, FALSE)) %>%
  mutate(region = c(rep("unique", 4))) %>%
  bind_cols(
    bind_rows(
    familyStats(samples_c1),
    familyStats(samples_c2),
    familyStats(samples_c3),
    familyStats(samples_c4)
  ))

familyEstimates %>%
  knitr::kable()
```

Vizualisation
```{r}
ggplot(familyEstimates %>%
         mutate(set = fct_inorder(set)),
       aes(x=set, 
           y=relVar.total,
           ymin=lower.total,
           ymax=upper.total)) +  
  geom_errorbar(aes(size=no.childrenPerFamily), col = "grey") +
    geom_point(aes(size=no.childrenPerFamily), col="#008000", shape=18) + 
  geom_hline(yintercept = 0) + 
  labs(x=NULL, y="Family variance component") + 
  ggpubr::theme_pubr()

allEstimates %>%
    mutate(set = fct_inorder(set),
           factor = fct_relevel(factor, c("Residual", "batch", "familyNr", "Fixed"))) %>%
  ggplot(aes(y=relVar.total, fill=factor, x=set)) + 
    geom_bar(stat="identity") + 
    ggpubr::theme_pubr()
```


Weighted results
```{r}
wMeanEstimate <- weighted.mean(
  x=familyEstimates$relVar.total,
  w=familyEstimates$no.familys
)

wSdEstimate <- Hmisc::wtd.var(
  x=familyEstimates$relVar.total,
  w=familyEstimates$no.familys
) %>% sqrt()

wMeanEstimate
wMeanEstimate + wSdEstimate * c(-1.96,1.96)
```


Tables
------

```{r}
write_delim(allEstimates,
            here("compendium/analyses/varianceComponentEstimations/allEstimates.tsv"),
            delim = "\t")

write_delim(familyEstimates,
            here("compendium/analyses/varianceComponentEstimations/familyEstimates.tsv"),
            delim = "\t")

```

